spring:
  application:
    name: ai

  ai:





    openai:
      api-key: _




server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
      uri-encoding: UTF-8







