spring:
  application:
    name: ai

  ai:


    model:
      chat: none
      embedding: false

    vectorstore:
      mariadb:
        initialize-schema: true
    openai:
      api-key: _

  datasource:
    url: jdbc:mariadb://localhost:3306/sys
    username: root
    password: 12345678


server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
      uri-encoding: UTF-8







open-router:
  api:
    key: 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

github_models:
  api:
    key: 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