spring.application.name=ai
server.port=8083

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8


# ????????????? ???????? ??????
spring.ai.ollama.chat.options.model=gemma3:4b

spring.ai.ollama.embedding.options.model=qwen3-embedding:0.6b

spring.ai.ollama.chat.options.max-tokens=128000


spring.datasource.url = jdbc:mariadb://localhost:3306/sys
spring.datasource.username = root
spring.datasource.password = 12345678

spring.ai.vectorstore.mariadb.initialize-schema = true


