spring:
  application:
    name: ai

  ai:


    model:
      chat: none
      embedding: false

    vectorstore:
      mariadb:
        initialize-schema: true
    openai:
      api-key: _

  datasource:
    url: jdbc:mariadb://localhost:3306/sys
    username: root
    password: 12345678


server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
      uri-encoding: UTF-8







open-router:
  api:
    key: open_router_api_key

github_models:
  api:
    key: github_models_api_key